apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.84.3.15/api"
  NEXTAUTH_URL: "http://3.84.3.15"
  NEXTAUTH_SECRET: "izRNrM7cRTI+FxI8SAVHSU9hqgkcy39A+vnR6OWJlR4="
  JWT_SECRET: "a87a7144507029e80c90c6c28ac13b63de62030fc74d87723ba44a1059c841bb"
