apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "a87a7144507029e80c90c6c28ac13b63de62030fc74d87723ba44a1059c841bb"
  NEXTAUTH_SECRET: "izRNrM7cRTI+FxI8SAVHSU9hqgkcy39A+vnR6OWJlR4="
